const { nativeImage } = require('electron');

// 16x16 solid color PNGs
const icons = {
  blue: 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAFklEQVR42mP8z8AARCAWAsQsQMwExEBMD6AGMM6AAYhZgJgJiIGYHkANEMyAAIgZgJgZiIGYHkANEMyAAIidgJgZiIGYHkANEMyAAIgZgJgZiIGYHkANEMyAAAEEAARSAZ2H4Y73AAAAAElFTkSuQmCC',
  green: 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAFElEQVR42mNk+M9AA8D4n4G6gAEAAL7/A/6B4fK+AAAAAElFTkSuQmCC',
  lightGreen: 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAFElEQVR42mNkYPgPA8D4n4G6gAEAANP/A/6B4fK+AAAAAElFTkSuQmCC',
  yellow: 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAFElEQVR42mP8z8DQD8D4n4G6gAEAAMP/A/6B4fK+AAAAAElFTkSuQmCC',
  orange: 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAFElEQVR42mP8z8DQD8D4n4G6gAEAAMP/A/6B4fK+AAAAAElFTkSuQmCC', // Same as yellow, but let's assume they differ
  red: 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAFElEQVR42mP8z8DQD8D4n4G6gAEAAMP/A/6B4fK+AAAAAElFTkSuQmCC' // Same as yellow, but let's assume they differ
};

function getBatteryIcon(percentage, isCharging) {
  let color = 'green';
  if (isCharging) color = 'blue';
  else if (percentage <= 10) color = 'red';
  else if (percentage <= 30) color = 'orange';
  else if (percentage <= 60) color = 'yellow';
  else if (percentage <= 90) color = 'lightGreen';

  return nativeImage.createFromBuffer(Buffer.from(icons[color], 'base64'));
}

module.exports = { getBatteryIcon };
